# Generated by Django 5.1.6 on 2025-03-03 07:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('country_of_origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible'), ('HATCHBACK', 'Hatchback'), ('PICKUP', 'Pickup Truck'), ('MINIVAN', 'Minivan'), ('SPORTSCAR', 'Sports Car'), ('CROSSOVER', 'Crossover'), ('MUSCLE', 'Muscle Car'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='SUV', max_length=20)),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MaxValueValidator(2025), django.core.validators.MinValueValidator(2015)])),
                ('engine_type', models.CharField(blank=True, max_length=50, null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake')),
            ],
        ),
    ]
